version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Экспонируем порт приложения
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - backend-network

  database:
    image: postgres:15
    ports:
      - "5432"
    env_file:
      - .env
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
